### PR TITLE
Enhance json schema

### PR DESCRIPTION
**Pull request by EmilyGraceSeville7cf**
- enable intellisence for programs/*.json configs
- add repo url to schema hints
- add examples for properties
- disallow space only strings for properties

### CODE REVIEW

**Comment by b3nj5m1n** [comment]
First of all, this is very cool, thank you for implementing it!

I believe the failed unit test is because some of the program configs don't follow the stricter rules you've specified. (Mainly that the help can't be empty)

Here's the list of failing configs:
```
programs/bazaar.json: fail: files.0.help: Must not validate the schema (not)
programs/antimicrox.json: fail: files.0.help: String length must be greater than or equal to 1
programs/antimicrox.json: fail: files.1.help: String length must be greater than or equal to 1
programs/steam.json: fail: files.0.help: String length must be greater than or equal to 1
programs/steam.json: fail: files.1.help: String length must be greater than or equal to 1
programs/expo.json: fail: files.0.help: String length must be greater than or equal to 1
programs/ledger.json: fail: files.0.help: Must not validate the schema (not)
programs/mysql.json: fail: files.0.help: String length must be greater than or equal to 1
programs/mysql.json: fail: files.1.help: String length must be greater than or equal to 1
programs/tlauncher.json: fail: files.0.help: String length must be greater than or equal to 1
programs/tlauncher.json: fail: files.1.help: String length must be greater than or equal to 1
```

I'll try to fix these, but it may take me a while since exams are coming up. If anyone wants to help, just update the help sections in those configs so they're not empty anymore and submit a PR for them.

**Comment by EmilyGraceSeville7cf** [comment]
> I'll try to fix these, but it may take me a while since exams are coming up. If anyone wants to help, just update the help sections in those configs so they're not empty anymore and submit a PR for them.

As a quick workaround (as I don't know your code internals) I've added a new suggested value `Not provided` for cases user don't know how to fill `files.<file>.help`. And fixed all of this errors like this.

**Comment by b3nj5m1n** [comment]
Should be fixed with #374, could you update your branch?

**Comment by EmilyGraceSeville7cf** [comment]
@b3nj5m1n, I did it. ;)

**Comment by b3nj5m1n** [comment]
Alright, I think we're good to go, thank you again for this!

**Pull request merged**
